// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorebaseTechnicalChallenge.Repository;

#nullable disable

namespace NorebaseTechnicalChallenge.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NorebaseTechnicalChallenge.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"), 1L, 1);

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            LikeCount = 0
                        },
                        new
                        {
                            ArticleId = 2,
                            LikeCount = 0
                        },
                        new
                        {
                            ArticleId = 3,
                            LikeCount = 0
                        },
                        new
                        {
                            ArticleId = 4,
                            LikeCount = 0
                        },
                        new
                        {
                            ArticleId = 5,
                            LikeCount = 0
                        },
                        new
                        {
                            ArticleId = 6,
                            LikeCount = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
